<script lang="ts" setup>
const { maxTokens } = useSettings()

const maxTokensInput = syncStorageRef(maxTokens)
</script>

<template>
    <div>
        <div mt-10 font-bold text-color mb-6 text-5>
            Options
        </div>
        <div flex="~ col" gap-1>
            <div text-color font-bold>
                Max Tokens
            </div>
            <div text-color-lighter text-14px>
                Limits the number of tokens that can be generated by the model.
            </div>
            <UInput
                v-model="maxTokensInput"
                placeholder="Openai max tokens"
                w-full text-gray-5 dark:text-gray-1
            />
        </div>
    </div>
</template>
